### ISSUE TITLE
Search engines might have the query inside the url

### ISSUE THREAD

**Issue by dvorapa** [G-Ray/pikatorrent#107]
My favourite search engine can't be added, because its url looks like this:

https://www.example.com/search/my favourite torrent/1/

**Comment by G-Ray** [comment]
Perfect timing, the new version v0.8.x allows to specify "%s" as a placeholder. 

You should be able to set you search engine as "https://www.example.com/search/%s/1/"

**Comment by dvorapa** [comment]
Perfect, yes, currently Microsoft Store.
