### ISSUE TITLE
I cant install or use PikaTorrent

### ISSUE THREAD

**Issue by nyouness** [G-Ray/pikatorrent#24]
Hi first using PikaTorrent , when i open v0.2.0 it closed by it self but it keep running on task manager on windows and when i use v0.1.4 it tell me to install npm -g pikatorrent and when i tried to install it it gave me error  :
[2023-06-21T20_37_19_415Z-debug-0.log](https://github.com/G-Ray/pikatorrent/files/11825985/2023-06-21T20_37_19_415Z-debug-0.log)

**Comment by nyouness** [comment]
Thank you for your reply and making this project , i'm newbie and i don't have experience in this stuff i only download and use and edit basic stuff :) , sorry cant give you the right answer.
Is PikaTorrent works like Popcorn Time (Movies and TV Shows) and Miru (Anime) ? i mean you can watch torrent or magnet before it completed downloads on external players , because the build looks like them

**Comment by G-Ray** [comment]
I just released v0.2.1 which should fix the crash on windows if you want to try :hugs: 

PikaTorrent will never promote any copyrighted content.
However, streaming while downloading is a planned feature. :play_or_pause_button:

**Comment by G-Ray** [comment]
So this was specific to windows where the is no stdout/stderr for GUI apps.
Fixed in transmission upstream https://github.com/transmission/transmission/pull/5675

We can close this, feel free to reopen a bug if your issue still occurs
