### ISSUE TITLE
[Android] Certain UI Elements going offscreen

### ISSUE THREAD

**Issue by Cyanide-1** [G-Ray/pikatorrent#93]
Certain UI Elements go off-screen as shown in here, Maybe due to screen size?

![Screenshot_20230914_063331_pikatorrent](https://github.com/G-Ray/pikatorrent/assets/136278181/461413a1-4646-4d7e-92ec-a47a2b4ce35c)

**Comment by G-Ray** [comment]
Fixed with 7e18510299d304c3f34f9296827a8074e16b21a5
Feel free to open other issues if other elements are off screens

**Comment by Cyanide-1** [comment]
thanks
